version: '3.2'
services:
  user_manager:
    tty: true
    container_name: user_manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_KEY=0123456789ABCDEF0123456789ABCDEF
    ports:
      - 8080:8080
    networks:
      - lab02-network

  product_manager:
    tty: true
    container_name: product_manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    networks:
      - lab02-network

networks:
  lab02-network:
    driver: "bridge"
    external: false